# Build from repo root: docker build -t unit3dup -f Docker/dockerfile .

FROM python:3.11-slim

# Set the username as your Host
ARG USERNAME=pc

# environment
ENV VIRTUAL_ENV=/home/$USERNAME/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies and clean
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sudo \
        ffmpeg \
        poppler-utils \
        libmediainfo-dev \
        build-essential \
        python3-venv \
        python3-dev \
        && rm -rf /var/lib/apt/lists/*

# Crea il gruppo con ID 1000 e poi l'utente $USERNAME
RUN groupadd -g 1000 $USERNAME && \
    useradd $USERNAME -u 1000 -g 1000 -m -s /bin/bash && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    
    
# Set the user
USER $USERNAME
WORKDIR /home/$USERNAME

# Create virtual env and upgrade pip
RUN python3 -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip

# Copy source and install from source
COPY --chown=$USERNAME:$USERNAME . /home/$USERNAME/app
WORKDIR /home/$USERNAME/app
RUN pip install --no-cache-dir .
WORKDIR /home/$USERNAME

# Set the entry point ( see pyproject.toml)
ENTRYPOINT ["unit3dup"]